### ISSUE TITLE
Publish on Maven repository [$10]

### ISSUE THREAD

**Issue by javydreamercsw** [travispessetto/OrigamiSMTP#1]
Would be great to have it available via Maven/Gradle. I've done it this way in other open source projects: http://central.sonatype.org/pages/apache-maven.html

**Comment by travispessetto** [comment]
Thank you for your advice.  I will look into this when I get time.  In the meantime, if there is another developer who would like to create Maven/Gradle scripts there is a $10 bounty.

**Comment by javydreamercsw** [comment]
I can do Maven but will need help with the rest of the setup.

**Comment by travispessetto** [comment]
What do you need help with?  I generally just use Eclipse projects and have once created an Ant build file for [OrigamiGUI](https://github.com/travispessetto/OrigamiGUI) but that is it.   So, I am not sure what exactly you will need besides that com.pessetto.main.OrigamiSMTP is the main class.

**Comment by javydreamercsw** [comment]
To my knowledge that PR does it. Test it and let me know. Without unit tests, etc. is hard to tell.

**Comment by javydreamercsw** [comment]
I was unable to figure out what some files are for as I saw no reference to them. So I'm sure I'm missing something.

**Comment by javydreamercsw** [comment]
The process to have it published I suggest you do it yourself as you should have control over that in case I'm not around.

**Comment by travispessetto** [comment]
I will take a look at the pull request.  Those files may not have a purpose as I have ran into dead code.  I need to refactor.  I will also put unit tests on my to do list.

**Comment by javydreamercsw** [comment]
Among other things I removed the jar file that was in the root folder and updated Travis to use the one from the build (in target directory).

**Comment by travispessetto** [comment]
Merged with master.  Working on getting it published.

**Comment by javydreamercsw** [comment]
Let me know if you need some assistance on that process.

**Comment by travispessetto** [comment]
Snapshot released to ossrh. Will deploy a release later.

**Comment by travispessetto** [comment]
Release promoted waiting on Jira Ticket.  Closing issue.
