### ISSUE TITLE
GUIDE : Setup on Manjaro Linux (or Arch)

### ISSUE THREAD

**Issue by Powerock38** [travispessetto/OrigamiSMTP#14]
If you get the error "Error: JavaFX runtime components are missing, and are required to run this application"

install the package [java-openjfx](https://archlinux.org/packages/extra/x86_64/java-openjfx/)

and launch the .jar with :

`java --module-path /usr/lib/jvm/java-17-openjdk/lib/javafx.controls.jar:/usr/lib/jvm/java-17-openjdk/lib/javafx.fxml.jar:/usr/lib/jvm/java-17-openjdk/lib/javafx.graphics.jar:/usr/lib/jvm/java-17-openjdk/lib/javafx.base.jar:/usr/lib/jvm/java-17-openjdk/lib/javafx.web.jar:/usr/lib/jvm/java-17-openjdk/lib/javafx.media.jar --add-modules javafx.controls,javafx.fxml,javafx.web,javafx.media -jar origami-smtp.jar`

also, be sure to use the jar from SourceForge and not the outdated one in the Releases tab of this repo

**Comment by travispessetto** [comment]
I am working on modularizing Origami SMTP so that these steps will no longer be required.

**Comment by travispessetto** [comment]
Fixed by shading Javafx files into the jar file with latest commit.  Next release should allow you to run java -jar origami-smtp.jar
