### ISSUE TITLE
Create accounts with username and password.

### ISSUE THREAD

**Issue by javydreamercsw** [travispessetto/OrigamiSMTP#3]
It would be useful to be able to create accounts you can send emails too and retrieve them later. This is part of the functionality I'm looking for not provided yet.

**Comment by travispessetto** [comment]
I have thought about a couple of things:

1.  Create an inbox per to address received which will be able to be accessed in the GUI
2.  Have a search filter for the to addresses

Please provide more information of what exactly you are looking for.

**Comment by javydreamercsw** [comment]
Basically I'm looking into this for unit tests. I would like to:

1. Set up the server.
1. Create one or more accounts (email, username, password).
1. From the email source (i.e. application being tested) send emails.
1. Retrieve emails from the user's inbox in order to check outcome (acceptance criteria of the unit test).

**Comment by travispessetto** [comment]
This is interesting and I need to think about it some more.  In order to make a more informed decision I need to know if you will be looking for bounced email messages.  The current setup is designed to be catch all and I anticipated keeping it that way.

There is plans for IMAP support that should allow more applications to be unit tested.  While it is a pain in the butt you could probably get some unit testing from the system if you are using Java.  You would need a copy of the jar file, a RunListener, and a few threads (similar to how the GUI works).

**Comment by javydreamercsw** [comment]
Right now I'm not looking for bounced emails. I just want to make sure the email my system sent was received on the different formats, plain SMTP, TLS, SSL, etc.

**Comment by travispessetto** [comment]
Are you just looking for Java or are you looking for compatibility with a range of languages?

**Comment by javydreamercsw** [comment]
I'm only interested in Java right now.

**Comment by travispessetto** [comment]
Alright, I will try writing a Java library that wraps Origami SMTP for testing.  I am not sure when I will have enough time to write it but will try to get it done within the next couple of weeks.

**Comment by travispessetto** [comment]
While it is not the best I implemented a basic library that will let you get the newest message from the server and compare any of its fields with the value you are expecting.  See [this test](https://github.com/travispessetto/OrigamiSMTP/blob/441e53143de71c45292017a07864d8f7360f9446/src/test/java/com/pessetto/origamismtp/testing/TestSMTPServerTest.java) for an example.

**Comment by travispessetto** [comment]
I made the basic test API a little easier to use.  See [this test](https://github.com/travispessetto/OrigamiSMTP/blob/cbb5b4b51638351e5170679b5f640778e8982511/src/test/java/com/pessetto/origamismtp/testing/TestSMTPServerTest.java) for an example.

**Comment by travispessetto** [comment]
At this time separate user accounts are not in the goal of this project.
