### ISSUE TITLE
[HELP] TLS startup failed (connect(): error:0407008A

### ISSUE THREAD

**Issue by un4ckn0wl3z** [travispessetto/OrigamiSMTP#4]
i use Swaks to try connect the OrigamiSMTP with TLS Support i already add CA to Trusted ROOT

and execute this command
**perl swaks.pl -t john.doe@example.com -f jane.doe@example.com -s localhost -p 587 -tls --tls-verify --tls-ca-path Origami_CA.crt**

result failed below ....

=== Trying localhost:587...
=== Connected to localhost.
<-  220 127.0.0.1 SMTP Ready
 -> EHLO DESKTOP-ISVG1G8
<-  250-localhost WELCOME TLS ENABLED
<-  250-AUTH PLAIN
<-  250 STARTTLS
 -> STARTTLS
<-  220 Ready to start TLS
TLS startup failed (connect(): error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding)
STARTTLS attempted but failed

**Comment by travispessetto** [comment]
I've started to look into this.  However, I am having a hard time tracing it.   There are several things that it could be.

**Comment by travispessetto** [comment]
It looks like the readme is referencing an old version of the root certificate.  You need to use [this one](https://raw.githubusercontent.com/travispessetto/OrigamiSMTP/master/src/main/resources/certs/CA/Origami_CA.crt) from the current master branch.  I'll fix this in the readme.
