### ISSUE TITLE
Email Details Not Appearing

### ISSUE THREAD

**Issue by trymeouteh** [travispessetto/OrigamiSMTP#6]
I am using XAMPP with OrigamiSTMP and with this simple PHP file I made I do get the emails in OrigamiSTMP but in OrigamiSTMP email under the Details tab it does not show From, To, Subject or Content.

```
<?php

mail('me@mail.com', 'MySubject', 'Message 123...');

?>
```

**Comment by travispessetto** [comment]
Thank you for reporting the issue.  I have fixed it in the OrigamiGUI project.  Please install the new 1.7.1 version from https://travispessetto.github.io/OrigamiSMTP/.
